# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * auth_brute_force
# 
# Translators:
# FIRST AUTHOR <EMAIL@ADDRESS>, 2014
# Hotellook, 2014
# Rudolf Schnapka <rs@techno-flex.de>, 2016
msgid ""
msgstr ""
"Project-Id-Version: server-tools (8.0)\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2016-12-24 05:31+0000\n"
"PO-Revision-Date: 2016-12-27 08:22+0000\n"
"Last-Translator: OCA Transbot <transbot@odoo-community.org>\n"
"Language-Team: Russian (http://www.transifex.com/oca/OCA-server-tools-8-0/language/ru/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Language: ru\n"
"Plural-Forms: nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);\n"

#. module: auth_brute_force
#: field:res.banned.remote,active:0
msgid "Active"
msgstr "Активно"

#. module: auth_brute_force
#: field:res.authentication.attempt,attempt_date:0
msgid "Attempt Date"
msgstr "Дата попытки"

#. module: auth_brute_force
#: field:res.banned.remote,attempt_ids:0
msgid "Attempts"
msgstr "Попыток"

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_authentication_attempt
#: model:ir.ui.menu,name:auth_brute_force.menu_res_authentication_attempt
msgid "Authentication Attempts"
msgstr "Попыток авторизации"

#. module: auth_brute_force
#: field:res.authentication.attempt,result:0
msgid "Authentication Result"
msgstr "Результат авторизации"

#. module: auth_brute_force
#: field:res.banned.remote,ban_date:0
msgid "Ban Date"
msgstr "Дата блокировки"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:34
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Banned"
msgstr "Заблокирован"

#. module: auth_brute_force
#: model:ir.actions.act_window,name:auth_brute_force.action_res_banned_remote
#: model:ir.ui.menu,name:auth_brute_force.menu_res_banned_remote
msgid "Banned Remotes"
msgstr "Заблокированные "

#. module: auth_brute_force
#: field:res.authentication.attempt,create_uid:0
#: field:res.banned.remote,create_uid:0
msgid "Created by"
msgstr "Создано"

#. module: auth_brute_force
#: field:res.authentication.attempt,create_date:0
#: field:res.banned.remote,create_date:0
msgid "Created on"
msgstr "Создан"

#. module: auth_brute_force
#: field:res.banned.remote,description:0
msgid "Description"
msgstr "Описание"

#. module: auth_brute_force
#: field:res.authentication.attempt,display_name:0
#: field:res.banned.remote,display_name:0
msgid "Display Name"
msgstr "Отображаемое имя"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:33
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Failed"
msgstr "Неудачно"

#. module: auth_brute_force
#: field:res.authentication.attempt,id:0 field:res.banned.remote,id:0
msgid "ID"
msgstr "ID"

#. module: auth_brute_force
#: field:res.authentication.attempt,__last_update:0
#: field:res.banned.remote,__last_update:0
msgid "Last Modified on"
msgstr "Последный раз изменено"

#. module: auth_brute_force
#: field:res.authentication.attempt,write_uid:0
#: field:res.banned.remote,write_uid:0
msgid "Last Updated by"
msgstr "Последний раз обновлено"

#. module: auth_brute_force
#: field:res.authentication.attempt,write_date:0
#: field:res.banned.remote,write_date:0
msgid "Last Updated on"
msgstr "Последний раз обновлено"

#. module: auth_brute_force
#: field:res.authentication.attempt,remote:0 field:res.banned.remote,remote:0
msgid "Remote ID"
msgstr "Внешний ID"

#. module: auth_brute_force
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
msgid "Successful"
msgstr "Успешно"

#. module: auth_brute_force
#: code:addons/auth_brute_force/models/res_authentication_attempt.py:32
#: selection:res.authentication.attempt,result:0
#, python-format
msgid "Successfull"
msgstr "Успешно"

#. module: auth_brute_force
#: field:res.authentication.attempt,login:0
msgid "Tried Login"
msgstr "Попыток входа"

#. module: auth_brute_force
#: help:res.banned.remote,active:0
msgid "Uncheck this box to unban the remote"
msgstr "Снимите отметку, чтобы разблокировать"

#. module: auth_brute_force
#: view:res.authentication.attempt:auth_brute_force.view_res_authentication_attempt_search
msgid "Without Success"
msgstr "Безуспешно"
